SCR_MissionHeaderCombatOps {
 World "{0341C6D04CAED367}worlds/Training_Arland/TTT_Arland_Training.ent"
 m_sName "TTT Training Arland V2"
 m_sAuthor "Rod3ox, Andy"
 m_sDescription "Grundlagentraining für das TTT"
 m_sDetails "Grundlagentraining für das TTT"
 m_sIcon "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sLoadingScreen "{E188A17B88D252DB}UI/Textures/MissionLoadingScreens/LoadingScreenSurvival.edds"
 m_sPreviewImage "{E188A17B88D252DB}UI/Textures/MissionLoadingScreens/LoadingScreenSurvival.edds"
 m_sGameMode "TTT Arland Training V2"
 m_iPlayerCount 48
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bIsArmavisionAllowedInMP 1
 m_ACE_Settings ACE_MissionHeaderSettings "{6959112EEBA9099A}" {
  m_ACE_Medical_Core ACE_Medical_Core_Settings "{6959112EE42AA659}" {
   m_fSecondChanceOnHead 1
  }
  m_ACE_Finger_Settings ACE_Finger_Settings "{6959112EE070D04A}" {
  }
  m_ACE_Medical_Hitzones ACE_Medical_Hitzones_Settings "{6959112EE171A9DD}" {
   m_fSecondChanceOnHeart 1
  }
 }
}