SCR_MissionHeaderCombatOps {
 World "{0341C6D04CAED367}worlds/Training_Arland/TTT_Arland_Training.ent"
 m_sName "TTT Training Arland V2"
 m_sAuthor "Rod3ox, Andy"
 m_sDescription "Grundlagentraining für das TTT"
 m_sDetails "Grundlagentraining für das TTT"
 m_sIcon "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sLoadingScreen "{E188A17B88D252DB}UI/Textures/MissionLoadingScreens/LoadingScreenSurvival.edds"
 m_sPreviewImage "{E188A17B88D252DB}UI/Textures/MissionLoadingScreens/LoadingScreenSurvival.edds"
 m_sGameMode "TTT Arland Training V2"
 m_iPlayerCount 48
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bIsArmavisionAllowedInMP 1
 m_ACE_Settings ACE_MissionHeaderSettings "{6959112EEBA9099A}" {
  m_ACE_Medical_Core ACE_Medical_Core_Settings "{6959112EE42AA659}" {
   m_fDefaultResilienceRegenScale 0.1
   m_fResilienceDamageScale 0.7
   m_fMinHealthScaledForEpinephrine 0.4
   m_fBleedingRateScale 0.1
   m_fSecondChanceResilienceRegenScale 0.5
   m_fSecondChanceOnHead 1
   m_bSecondChanceForFallDamageEnabled 1
  }
  m_ACE_Finger_Settings ACE_Finger_Settings "{6959112EE070D04A}" {
  }
  m_ACE_Medical_Hitzones ACE_Medical_Hitzones_Settings "{6959112EE171A9DD}" {
   m_fSecondChanceOnHeart 1
  }
  m_ACE_Medical_Circulation ACE_Medical_Circulation_Settings "{697E9B1A6932F6D5}" {
   m_UnstableThresholds ACE_Medical_VitalStateThresholdsConfig "{697E9B1A619EBBA3}" {
    m_fHeartRateLowBPM 40
    m_fHeartRateHighBPM 145
    m_fMeanArterialPressureLowKPA 7.11
    m_fMeanArterialPressureHighKPA 29.5
    m_fMaxHeartForMeanArterialPressureLowBPM 40
    m_eBloodState CLASS_2_HEMORRHAGE
   }
   m_CriticalThresholds ACE_Medical_VitalStateThresholdsConfig "{697E9B1A0B058421}" {
    m_fHeartRateLowBPM 30
    m_fHeartRateHighBPM 220
    m_fMeanArterialPressureLowKPA 5.21
    m_fMeanArterialPressureHighKPA 29.5
    m_fMaxHeartForMeanArterialPressureLowBPM 30
    m_eBloodState CLASS_3_HEMORRHAGE
   }
   m_CardiacArrestThresholds ACE_Medical_VitalStateThresholdsConfig "{697E9B1A3B33D2A2}" {
    m_fHeartRateLowBPM 20
    m_fHeartRateHighBPM 220
    m_fMeanArterialPressureLowKPA 5.21
    m_fMeanArterialPressureHighKPA 29.5
    m_fMaxHeartForMeanArterialPressureLowBPM 30
    m_eBloodState CLASS_4_HEMORRHAGE
   }
   m_CardiacArrestDamageEffect ACE_Medical_CardiacArrestDamageEffect "{697E9B1A2988E335}" {
    m_fBrainDamageRate 0.18
    m_fEffectStartDelayS 30
   }
   m_fCPRStrokeVolumeScale 0.3
   m_fCPRSuccessCheckTimeoutS 20
   m_fCPRSuccessChanceMin 0.1
   m_fCPRSuccessChanceMax 0.8
   m_fAmmoniumCarbonateSuccessChanceMin 1
   m_fCardiacArrestMaxTotalBleedingRate 2
  }
  m_ACE_Medical_Breathing ACE_Medical_Breathing_Settings "{697E9B1BC645E4D9}" {
   m_fAirwayObstructionChance 0.2
   m_fVomitChancePerMinute 0.15
   m_fVomitCooldown 15
   m_fPneumothoraxChance 0.4
   m_fPneumothoraxDeteriorationChancePerMinute 0.4
   m_fMaxPneumothoraxScale 0.5
   m_fPneumothoraxScaleDeteriorationStep 0.2
   m_fTensionPneumothoraxChance 0.1
   m_fDeteriorateToTensionPneumothoraxChancePerMinute 0.2
  }
  m_ACE_Overheating ACE_Overheating_Settings "{697E9B1B9DC27A36}" {
  }
 }
}